### ISSUE TITLE
Review docs

### ISSUE THREAD

**Issue by stropitek** [image-js/iobuffer#29]
@targos can you do a quick review of the new api and it's documentation?

I've built the API documentation with jsdoc3 and added a little working example in the readme

I'll do a release after approval ;-)

**Comment by targos** [comment]
Bug in documentation.js: TypedArray is not recognized as a type.
https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/TypedArray

**Comment by targos** [comment]
Opened an issue in documentation.js about TypedArray
