### ISSUE TITLE
Reading variable length Int

### ISSUE THREAD

**Issue by dderevjanik** [image-js/iobuffer#49]
Hello,
is it possible to read int with non-standard bytes length? e.g. 4

Similar to <https://stackoverflow.com/questions/30911185/javascript-reading-3-bytes-buffer-as-an-integer>

**Comment by lpatiny** [comment]
I had a similar problem parsing [uavcan](https://uavcan.org/) packets

If the data are not too big and time is not super critical you can convert your data to a BigInteger and then use

https://github.com/lpatiny/uavcan/blob/master/src/data/parser/util/parseInt.js
