### ISSUE TITLE
question: back n bytes

### ISSUE THREAD

**Issue by santimirandarp** [image-js/iobuffer#51]
Given that there is `buffer.skip()` would it be worth to have a `buffer.back(n)` ?

I was just writing (sorry for the example)
```
  buffer.offset -= 4;//back from parameter reading
  const sequences = buffer.readUint16();
  buffer.skip(2) //now skip the parameters
```
And wondered about it. I am aware that skip(-2) should do, but it may not be semantically that useful.

**Comment by targos** [comment]
adding `buffer.back(n)` sgtm. would you like to make a PR?

**Comment by santimirandarp** [comment]
Yes, I would like to try. Tomorrow if that is fine.
